"""vtubers table

Revision ID: 1332e7905814
Revises: a8032df3ef07
Create Date: 2021-04-13 15:34:09.402282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1332e7905814'
down_revision = 'a8032df3ef07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('timestamp', sa.Integer(), nullable=True))
    op.add_column('vtuber', sa.Column('fans', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vtuber', 'fans')
    op.drop_column('video', 'timestamp')
    # ### end Alembic commands ###
